---
- hosts: "{{ host }}"
  #become: true
  vars:
    default_container_name: profile-app
    default_container_image: samer1984/profile-description:latest

  tasks:
    - name: Pull default Docker image
      docker_image:
        name: "{{ default_container_image }}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        detach: yes
        ports:
        - "5000:5000"